### ISSUE TITLE
Terrible license makes the project unusable by practically everyone

### ISSUE THREAD

**Issue by hopeseekr** [tuqqu/gender-detector#1]
The GNU Public License v3.0 is TERRIBLE for a *library*!!

No one is going to adopt this! It's worse than a proprietary license. The only way you could make it worse is if it were the Affero License.

See [**Can I use GPL libraries in a closed source project if only the output is distributed?**](https://opensource.stackexchange.com/questions/2338/can-i-use-gpl-libraries-in-a-closed-source-project-if-only-the-output-is-distrib).  Answer **NO**.

And: [**GNU Public License is all but free and you should never use it**](https://dev.to/matteojoliveau/gnu-public-license-is-all-but-free-and-you-should-never-use-it-3fk)

At a minimum, choose the Lesser GPL, or LGPL. But really, you're better off with the [**Creative Commons ShareALike Attribution License**](https://creativecommons.org/licenses/by-sa/3.0/us/).

**Comment by tuqqu** [comment]
Thanks for pointing that out. Changed the package license to a more appropriate MIT License.

**Comment by tuqqu** [comment]
closing the issue as it seems it has been resolved with the MIT license.
