### ISSUE TITLE
Rename the component to current standard terms.

### ISSUE THREAD

**Issue by PurHur** [tuqqu/gender-detector#2]
The component should be called **gender-assumer** to match the current political english terms.

**Comment by tuqqu** [comment]
Hello. I made a quick search and it seems that gender detection is quite a widespread term with a lot of packages using it. It is even a name of one of the GitHub topics. While the usage of 'gender assumption/assumer' is very rare (in the programming world at least). 

Can you provide some source proving your point of view?

**Comment by tuqqu** [comment]
Please reopen if you feel the issue unresolved
