### ISSUE TITLE
How to expand nam_dict.txt to add new names?

### ISSUE THREAD

**Issue by draci1** [tuqqu/gender-detector#3]
I need to add some other names but there are no instructions on how to edit nam_dict.txt, is the file generated by a program or is there a way to directly edit this file?

**Comment by tuqqu** [comment]
Hello.
This is the original file by Jörg Michael and should not really be edited directly. 

What you should do is to create your own dictionary file of the same format with the names you need and add it to the detector. 
```php
$genderDetector->addDictionaryFile('custom_file_path/another_dict.txt');
```
