### ISSUE TITLE
Terrible file format of nam_dict.txt

### ISSUE THREAD

**Issue by gvojtko** [tuqqu/gender-detector#4]
The file format and data entry method is not applicable for any name extension. Using spaces between characters is a bad way. For each name, it is necessary to calculate the number of spaces and at the same time monitor for which country I am entering data. It would be useful to use a file and template in csv, xml, json, yaml or other file format, which will allow you to clearly define names and countries.

**Comment by tuqqu** [comment]
Hello! Thanks for taking interest in this library. 

The `nam_dict.txt` file format is not ideal and rather odd, that's true, it comes from the original gender.c program written in I believe 2007.

I do not really see a point in supporting various file formats, as this library was basically built as a wrapper for the contents of this  `nam_dict.txt` file. Adding an option to add a custom dictionary file was trivial, so I implemented it.

There are similar libraries in other languages i.e [in ruby](https://github.com/bmuller/gender_detector), [in python](https://github.com/ferhatelmas/sexmachine/) that share the "file wrapper library" concept. I believe there are others as well. 

Thus, apart from adding complexity and dependencies (not all formats are natively supported by php), adding this option would present the whole package as a general purpose gender detecting tool to use in pair with some kind of data-providers (who would create them?), which it really isn't.
