### ISSUE TITLE
Number of genders

### ISSUE THREAD

**Issue by oceanapplications** [tuqqu/gender-detector#5]
The number of genders offered is astonishingly low. This is likely to assume someone's gender incorrectly. 

Assuming someone's gender can cause trauma and is violence.

**Comment by SeverinDK** [comment]
> The number of genders offered is astonishingly low. This is likely to assume someone's gender incorrectly.
> 
> Assuming someone's gender can cause trauma and is violence.

Then you should create your own package that returns any gender for any name. Problem solved :)
