### ISSUE TITLE
Invalid characters passed for attempted conversion, these have been ignored

### ISSUE THREAD

**Issue by hossein** [tuqqu/gender-detector#6]
Calling the following:

```
(new GenderDetector\GenderDetector())->detect('Saša');
```

will result in the PHP notice:

```
PHP Deprecated:  Invalid characters passed for attempted conversion, these have been ignored
```

The reason is somewhere inside the code `hexdec('-')` is being evaluated, but since PHP 7.4 [passing invalid characters to base conversion functions is deprecated](https://www.php.net/manual/en/migration74.deprecated.php#migration74.deprecated.core.invalid-base-characters).

Thanks for the good library.

**Comment by tuqqu** [comment]
Hello and thanks for reporting this bug.

A quick research showed that the issue occurred when parsing certain duplicated names that contained non-iso unicode characters.

I fixed the issue along with introducing other smaller improvements. You may want to check out the new release [v0.4](https://github.com/tuqqu/gender-detector/releases/tag/v0.4).
